### ISSUE TITLE
No singularize method

### ISSUE THREAD

**Issue by djsegal** [TotalVerb/EnglishText.jl#2]
Is there a way to add the dual of pluralize?

**Comment by TotalVerb** [comment]
The MIT-licensed Inflector.NET has this function, which is implemented using a [rule-based approach](https://github.com/srkirkland/Inflector/blob/85a5a317251a774a4b9abfba23c64b44448a6767/Inflector/Inflector.cs) like the current pluralizer. I think porting that code will be the easiest way.

**Comment by djsegal** [comment]
Thanks man! That was a quick turn around
